version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "yearly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "yearly"
